config/routes.rb
Jksharer::Application.routes.draw do
  
  resources :blog_types

  resources :resource_types

  resources :blogs

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: "main_pages#home"
  
  match '/', to: 'main_pages#home', via: 'get'
  match '/about', to: 'main_pages#about', via: 'get'
  match '/contact', to: 'main_pages#contact', via: 'get'
  match '/settings', to: 'main_pages#settings', via: 'get'
  match '/category', to: 'main_pages#category', via: 'get'
  
  match '/signup', to: 'users#new',   via: 'get'
  match '/signin', to: 'sessions#new',   via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  
end

app/controllers/resource_types_controller.rb
class ResourceTypesController < ApplicationController
  before_action :set_resource_type, only: [:show, :edit, :update, :destroy]
  before_action :check_if_logined
  
  # GET /resource_types
  # GET /resource_types.json
  def index
    @resource_types = ResourceType.all
  end

  # GET /resource_types/1
  # GET /resource_types/1.json
  def show
  end

  # GET /resource_types/new
  def new
    @resource_type = ResourceType.new
  end

  # GET /resource_types/1/edit
  def edit
  end

  # POST /resource_types
  # POST /resource_types.json
  def create
    @resource_type = ResourceType.new(resource_type_params)

    respond_to do |format|
      if @resource_type.save
        format.html { redirect_to resource_types_path, 
          notice: 'Resource type was successfully created.' }
        format.json { render action: 'show', 
          status: :created, location: @resource_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @resource_type.errors, 
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_types/1
  # PATCH/PUT /resource_types/1.json
  def update
    respond_to do |format|
      if @resource_type.update(resource_type_params)
        format.html { redirect_to @resource_type, notice: 'Resource type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resource_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_types/1
  # DELETE /resource_types/1.json
  def destroy
    if Blog.where(resource_type: @resource_type).count >= 1
      flash[:error] = "there are blogs associated with this resource type."
      redirect_to resource_types_path
    else 
      @resource_type.destroy
      respond_to do |format|
        format.html { redirect_to resource_types_url }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource_type
      @resource_type = ResourceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_type_params
      params.require(:resource_type).permit(:name)
    end
end

app/helpers/resource_types_helper.rb
module ResourceTypesHelper
end

app/views/resource_types/_form.html.erb
<%= form_for(@resource_type) do |f| %>
  <% if @resource_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_type.errors.count, "error") %> prohibited this resource_type from being saved:</h2>

      <ul>
      <% @resource_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_types/edit.html.erb
<h1>Editing resource_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource_type %> |
<%= link_to 'Back', resource_types_path %>

app/views/resource_types/index.html.erb
<h1>Resource Types</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Blogs</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resource_types.each do |resource_type| %>
      <tr>
        <td><%= link_to resource_type.name, resource_type %></td>
        <td>
          <%= Blog.where(resource_type: resource_type).count %></td>
        <td><%= link_to 'Edit', edit_resource_type_path(resource_type) %></td>
        <td><%= link_to 'Destroy', resource_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Type', new_resource_type_path, class: "btn btn-success active" %>

app/views/resource_types/new.html.erb
<h1>New resource_type</h1>

<%= render 'form' %>

<%= link_to 'Back', resource_types_path %>

app/views/resource_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @resource_type.name %>
</p>

<%= link_to 'Edit', edit_resource_type_path(@resource_type) %> |
<%= link_to 'Back', resource_types_path %>