config/routes.rb
Jksharer::Application.routes.draw do
  
  resources :blog_types

  resources :resource_types

  resources :blogs

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: "main_pages#home"
  
  match '/', to: 'main_pages#home', via: 'get'
  match '/about', to: 'main_pages#about', via: 'get'
  match '/contact', to: 'main_pages#contact', via: 'get'
  match '/settings', to: 'main_pages#settings', via: 'get'
  match '/category', to: 'main_pages#category', via: 'get'
  
  match '/signup', to: 'users#new',   via: 'get'
  match '/signin', to: 'sessions#new',   via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, :content, presence: :true
  
  belongs_to :resource_type
  belongs_to :blog_type
end

app/models/blog_type.rb
class BlogType < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :blogs
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :check_if_logined, only: [:index, :new, :edit, :create, :destroy]
  before_action :set_count, only: [:show]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order('created_at DESC').page(params[:page]).per_page(5)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    ps = blog_params
    @blog = Blog.new
    @blog.resource_type = ResourceType.find_by(name: ps[:resource_type])
    @blog.blog_type = BlogType.find_by(name: ps[:blog_type])
    @blog.title = ps[:title]
    @blog.content = ps[:content]
    @blog.read_count = 0
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, 
          notice: 'Blog was successfully created.' }
        format.json { render action: 'show', 
          status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, 
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    ps = blog_params
    @blog.resource_type = ResourceType.find_by(name: ps[:resource_type])
    @blog.blog_type = BlogType.find_by(name: ps[:blog_type])
    @blog.title = ps[:title]
    @blog.content = ps[:content]
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:resource_type, :blog_type, :title, :content )
    end

    def set_count
      @blog.read_count += 1
      @blog.save
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def resource_checked?(blog, radio_name)
    !blog.resource_type.nil? && (blog.resource_type.name == radio_name)
  end
  
  def blog_checked?(blog, radio_name)
    !blog.resource_type.nil? && (blog.blog_type.name == radio_name)
  end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :resource_type %>
    <% ResourceType.all.each do |t| %>
      <%= f.radio_button :resource_type, "#{t.name}", class: "form-control input-sm", 
        checked: resource_checked?(@blog, t.name) %>
      <span><%= t.name %></span>
    <% end %>
    <br/><br/>
    <!-- <%= f.select :resource_type, ResourceType.all.map { |t| t.name }, 
      prompt: "Select a type", class: "form-control input-sm" %> -->
    <%= f.label :blog_type %>
    <% BlogType.all.each do |t| %>
      <%= f.radio_button :blog_type, "#{t.name}", class: "form-control input-sm", 
        checked: blog_checked?(@blog, t.name) %>
      <span><%= t.name %></span>
    <% end %>
    <br/><br/>
    <!-- <%= f.select :blog_type, BlogType.all.map { |t| t.name }, 
      prompt: "Select a type", class: "form-control input-sm" %> -->
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :content %>
    <%= f.kindeditor :content %>
    
    <%= f.submit class: "btn btn-large btn-primary"%>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs Management</h1>

<%= link_to 'New Blog', new_blog_path, class: "btn btn-success active" %>
<div class="blogs table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Resource Type</th>
      <th>Blog Type</th>
      <th>Read Count</th>
      <th></th>
    </tr>
  </thead>

  <tbody>  
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.title, blog %></td>
        <td><%= blog.resource_type.name %></td>
        <td><%= blog.blog_type.name %></td>
        <td><%= blog.read_count %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
</div>
<%= link_to 'Source Type', resource_types_path, class: "btn btn-success" %>
<%= link_to 'Blog Type', blog_types_path, class: "btn btn-success" %>
<br>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="article">
    <h3 class="title"><%= link_to @blog.title, @blog %></h3>
    <span class="timestamp">
      <%= time_ago_in_words(@blog.created_at) %> ago
    </span>
    <span class="types">
        <%= link_to @blog.resource_type.name, controller: "main_pages", action: "category", 
          resource_type: @blog.resource_type.id %>        
        <%= link_to @blog.blog_type.name, controller: "main_pages", action: "category", 
          blog_type: @blog.blog_type.id %>    
    </span>
    <span class="read-count">浏览：<%= @blog.read_count/2  %>次</span>
    <div class="content-show">
      <%= raw @blog.content %>  
    </div>
</div>

app/views/blogs/tinymce_form.html.erb
<script type="text/javascript">
  tinymce.init({
    selector: "textarea",
    theme: "modern",
    plugins: [   
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor"
    ],
    toolbar1: "undo redo | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect",
    toolbar2: " searchreplace | bullist numlist | outdent indent blockquote | link unlink anchor image media code | inserttime preview | forecolor backcolor",
    toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker | visualchars visualblocks nonbreaking template pagebreak restoredraft",
    image_advtab: true,
    insertdatetime_formats: ["%Y.%m.%d", "%H:%M"]
  });
</script>

<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :resource_type %>
    <% ResourceType.all.each do |t| %>
      <%= f.radio_button :resource_type, "#{t.name}", class: "form-control input-sm", 
        checked: resource_checked?(@blog, t.name) %>
      <span><%= t.name %></span>
    <% end %>
    <br/><br/>
    <!-- <%= f.select :resource_type, ResourceType.all.map { |t| t.name }, 
      prompt: "Select a type", class: "form-control input-sm" %> -->
    <%= f.label :blog_type %>
    <% BlogType.all.each do |t| %>
      <%= f.radio_button :blog_type, "#{t.name}", class: "form-control input-sm", 
        checked: blog_checked?(@blog, t.name) %>
      <span><%= t.name %></span>
    <% end %>
    <br/><br/>
    <!-- <%= f.select :blog_type, BlogType.all.map { |t| t.name }, 
      prompt: "Select a type", class: "form-control input-sm" %> -->
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :content %>
    <%= f.text_area :content, :class => "tinymce", :rows => 20, :cols => 80, 
      :id => "blog-content" %>
  
    <%= f.submit class: "btn btn-large btn-primary"%>
<% end %>