config/routes.rb
Jksharer::Application.routes.draw do
  
  resources :blog_types

  resources :resource_types

  resources :blogs

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: "main_pages#home"
  
  match '/', to: 'main_pages#home', via: 'get'
  match '/about', to: 'main_pages#about', via: 'get'
  match '/contact', to: 'main_pages#contact', via: 'get'
  match '/settings', to: 'main_pages#settings', via: 'get'
  match '/category', to: 'main_pages#category', via: 'get'
  
  match '/signup', to: 'users#new',   via: 'get'
  match '/signin', to: 'sessions#new',   via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    <%= link_to "Zk's Blog", root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact Me", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Zk's Shared Blog", root_url, id: "logo" %>
      <nav>
        <ul class="nav pull-right nav-pills">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if sign_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Admin <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Blogs", blogs_path %></li>
                  <li><%= link_to "Users", users_path %></li>
                  <li><%= link_to "Modify Password", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                </ul> 
              </li> 
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>              
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= yield %> 
    <%= render 'layouts/footer' %>   
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </div>
</body>
</html>